#!/usr/bin/env bash

function get_firefox_window {
  dbus-send --session --dest=org.gnome.Shell --print-reply=literal /org/gnome/Shell/Extensions/Windows org.gnome.Shell.Extensions.Windows.List \
    | jq --exit-status '[.[] | select ((.in_current_workspace == true) and (.wm_class | startswith("firefox")))] | first | .id'
}

function raise_window {
  local -r win_id="${1:?}"
  gdbus call \
    --session \
    --dest org.gnome.Shell \
    --object-path /org/gnome/Shell/Extensions/Windows \
    --method org.gnome.Shell.Extensions.Windows.Activate "${win_id}" >/dev/null
}

if WIN_ID="$(get_firefox_window)"; then
  raise_window "${WIN_ID}"
  firefox --new-tab "$@"
else
  nohup firefox --new-window "$@" > /dev/null 2>&1 &
  sleep 0.5
  WIN_ID="$(get_firefox_window)"
  if [[ "${WIN_ID}" != "null" ]]; then
    raise_window "${WIN_ID}"
  fi
fi
